EBill/Models/BillDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using EBill.Models;

namespace EBill.Models
{
    public class BillDetail
    {
        public int Id { get; set; }
        public string CustomerName { get; set; }
        public string MobileNumber { get; set; }
        public string Address { get; set; }
        public int TotalAmount { get; set; }
        public List<Items> Items { get; set; }

        public BillDetail()
        {
            Items = new List<Items>();
        }
    }
}

EBill/Models/Items.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EBill.Models
{
    public class Items
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string Price { get; set; }
        public string Quantity { get; set; }
        public int ItemIndex { get; set; }
    }
}

EBill/Controllers/EBillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EBill.Models;
using EBill.Repository;

namespace EBill.Controllers
{
    public class EBillController : Controller
    {
        // GET: EBill
        public ActionResult Index()
        {
            Data data = new Data();
            var list = data.GetAllDetail();
            return View(list);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(BillDetail details)
        {
            Data data = new Data();
            data.SaveBillDetails(details);
            ModelState.Clear();
            return View();
        }

        public ActionResult CreateItem(Items item)
        {
            return PartialView("_CreateItem",item);
        }
        public ActionResult ViewBill(int Id)
        {
            Data data = new Data();
            var details = data.GetDetail(Id);
            return View(details);
        }
    }
}

EBill/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EBill.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

EBill/Views/EBill/Create.cshtml
@model EBill.Models.BillDetail
@{
    ViewBag.Title = "Create";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6 offset-3 shadow rounded">
            @using (Html.BeginForm())
            {
                <div class="mt-2">
                    <h3 class="text-center">Create E Bill</h3>
                </div>
                <div class="mb-3">
                    <label class="form-label">Customer Name</label>
                    @Html.TextBoxFor(modelItem => modelItem.CustomerName, new { @class = "form-control form-control-sm" })
                </div>
                <div class="mb-3">
                    <label class="form-label">Mobile Number</label>
                    @Html.TextBoxFor(modelItem => modelItem.MobileNumber, new { @class = "form-control form-control-sm" })
                </div>
                <div class="mb-3">
                    <label class="form-label">Address</label>
                    @Html.TextBoxFor(modelItem => modelItem.Address, new { @class = "form-control form-control-sm" })
                </div>
                <div class="mb-3">
                    <div class="mb-2">
                        <span class="h5">Items</span>
                        <button type="button" class="btn btn-sm btn-primary border float-end" data-bs-toggle="modal" data-bs-target="#modalbox">Add</button>
                    </div>
                    <table id="items" class="table table-striped table-responsive table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>Product Name</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-sm btn-success">Save</button>
                </div>
            }
        </div>        
    </div>
</div>
<div class="modal fade" id="modalbox" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="mb-3">
                    <label class="form-label">Product Name</label>
                    <input type="text" class="form-control form-control-sm" placeholder="Enter Product Name" id="productname" />
                </div>
                <div class="mb-3">
                    <label class="form-label">Price</label>
                    <input type="text" class="form-control form-control-sm" placeholder="Enter Price" id="price" />
                </div>
                <div class="mb-3">
                    <label class="form-label">Quantity</label>
                    <input type="text" class="form-control form-control-sm" placeholder="Enter Quantity" id="quantity" />
                </div>
                <div class="mb-3">
                    <button class="btn btn-sm btn-success" type="button" id="addItem">Add</button>
                    <button class="btn btn-sm btn-primary" type="button" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#addItem').click(function () {
            let productName = $('#productname').val();
            let price = $('#price').val();
            let quantity = $('#quantity').val();
            let ItemIndex = $('#items tbody tr').length;
            $.ajax({
                url: "/EBill/CreateItem",
                type: "POST",
                data: { productName, price, quantity, ItemIndex },
                success: function (resp) {
                    $('#items tbody').append(resp);
                    $('#productname').val("");
                    $('#price').val("");
                    $('#quantity').val("");
                },
                error: function (err) {
                    alert(err)
                }
            })
        })       
    })
</script>

EBill/Views/EBill/Index.cshtml
@model IEnumerable<EBill.Models.BillDetail>
@{
    ViewBag.Title = "E-Bill";
}

<div class="container shadow rounded mt-4">
    <div class="row">
        <div class="col-12">
            <h4>All Bills</h4>
            <table class="table table-responsive table-striped table-hover table-bordered text-center">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Customer Name</th>
                        <th>Mobile Number</th>
                        <th>Address</th>
                        <th>Total Amount</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.CustomerName</td>
                        <td>@item.MobileNumber</td>
                        <td>@item.Address</td>
                        <td>@item.TotalAmount</td>
                        <td>
                            @Html.ActionLink("View", "ViewBill","EBill",new {Id=item.Id},new { @clsss="btn btn-sm btn-light border"})
                        </td>
                    </tr>
                    }
                </tbody>
            </table>

        </div>

    </div>

</div>

EBill/Views/EBill/ViewBill.cshtml
@model EBill.Models.BillDetail

@{
    ViewBag.Title = "View Bill";
}

<div class="container shadow rounded mt-4">
    <div class="row">
        <div class="col-6">
            <h3 class="text-primary">Programming with Paul</h3>
            <pre>
 Address    : Lagos NG,
 Phone      : +2348055114101
 Website    : www.paulwebsite.com
   </pre>
        </div>
        <div class="offset-3 col-3">
            <h3 class="text-primary">E-Bill</h3>
            <pre>
Number :@Model.Id
</pre>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-3">
            <h4 class="bg-primary text-white">Bill</h4>
            <pre>
@Model.CustomerName
@Model.MobileNumber
@Model.Address
</pre>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-12">
            <table class="table table-bordered table-striped table-responsive">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Items)
                    {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.ProductName</td>
                        <td>@item.Price</td>
                        <td>@item.Quantity</td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-12">
            <h4 class="float-end">Total Amount : @Model.TotalAmount</h4>
        </div>

    </div>
</div>

EBill/Views/EBill/_CreateItem.cshtml
@model EBill.Models.Items

<tr id="row-@Model.ItemIndex">
    <td>
        @Model.ProductName
        <input type="hidden" name="Items[@Model.ItemIndex].ProductName" value="@Model.ProductName" />
    </td>
    <td>
        @Model.Price
        <input type="hidden" name="Items[@Model.ItemIndex].Price" value="@Model.Price" />
    </td>
    <td>
        @Model.Quantity
        <input type="hidden" name="Items[@Model.ItemIndex].Quantity" value="@Model.Quantity" />
    </td>
    <td><button type="button" class="btn btn-sm bg-danger text-white" onclick="RemoveItem(@Model.ItemIndex)">Remove</button></td>
</tr>

<script type="text/javascript">
    function RemoveItem(Id)
    {
        $('#row-' + Id).remove();
    }
</script>

EBill/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="container shadow mt-4 rounded">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="~/Content/Images/ebill 1.jpg" class="d-block w-100" style="height:300px" />
                    </div>
                    <div class="carousel-item">
                        <img src="~/Content/Images/ebill 2.jpg" class="d-block w-100" style="height:300px"/>
                    </div>
                    <div class="carousel-item">
                        <img src="~/Content/Images/ebill 3.png" class="d-block w-100" style="height:300px"/>
                    </div>
                </div>
            </div>
            <div class="mt-3 mb-3">
                <h2>E-Bill Application</h2>
            </div>
        </div>
    </div>
</div>

EBill/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body class="pt-0">
    <nav class="navbar navbar-expand-lg nav-light bg-light shadow sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">E-Bill</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">

                    @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link active" })
                    @Html.ActionLink("View Bills", "Index", "EBill", null, new { @class = "nav-link" })
                    @Html.ActionLink("Create Bill", "Create", "EBill", null, new { @class = "nav-link" })
                    
                </div>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>